name: HouseTable Project CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        env:
            CI: true
        strategy:
            matrix:
                node-version: [20.x]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
    deploy:
        needs: build
        strategy:
            matrix:
                node-version: [20.x]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Heroku CLI
              run: |
                  wget -qO- https://toolbelt.heroku.com/install.sh | sh
                  heroku --version

            - name: Deploy to Heroku
              run: |
                  heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
                  echo "machine git.heroku.com login _ password=${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
                  git push heroku HEAD:main
